[package]
name = "sqlorm"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["sqlorm-core", "sqlorm-macros"]

[workspace.dependencies]
sqlorm-core = { path = "sqlorm-core" }
sqlorm-macros = { path = "sqlorm-macros" }
async-trait = "0.1.8"
lazy_static = "1.5"
sqlx = { version = "0.8", features = ["chrono"] }
thiserror = "2"


[dependencies]
sqlorm-core.workspace = true
sqlorm-macros.workspace = true
async-trait.workspace = true
sqlx.workspace = true

[features]
default = []
mysql = ["sqlorm-core/mysql", "sqlorm-macros/mysql"]
postgres = ["sqlorm-core/postgres", "sqlorm-macros/postgres"]
sqlite = ["sqlorm-core/sqlite", "sqlorm-macros/sqlite"]
