version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: us
      POSTGRES_PASSWORD: pa
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: us
      POSTGRES_PASSWORD: pa
    ports:
      - "6666:5432"

volumes:
  pgdata:
