[package]
name = "migrations-helper"
version = "0.2.1"
edition = "2024"

[dependencies]
sqlorm = { path = "../../../", features = ["migrate"] }
sqlx = { version = "0.8.6", features = ["macros", "migrate"] }

[features]
default = []
postgres = ["sqlorm/postgres"]
sqlite = ["sqlorm/sqlite"]
